### ISSUE TITLE
画面比率によっては真っ白な画面になってしまう不具合

### ISSUE THREAD

**Issue by Kasugaccho** [nishidate-yuki/nishidate-yuki.github.io#1]
不具合の報告です。

（縦長表示の）スマートフォン及び画面比率が縦10:横13よりも横が短い表示のブラウザでは、正常にポートフォリオサイトが表示されず、真っ白な画面が表示されます。

**Comment by nishidate-yuki** [comment]
報告ありがとうございます。修正いたしました。
